// <auto-generated />
namespace MaryKey.Repositorio.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remover_drop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remover_drop));
        
        string IMigrationMetadata.Id
        {
            get { return "201605192329089_remover_drop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
